using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UWP.Beer.Models
{
    public class Enum
    {
        #region Países
        public enum Paises
        {
            Afeganistao = 1,
            Albania = 2,
            Argelia = 3,
            Andorra = 4,
            Angola = 5,
            Antigua = 6,
            Argentina = 7,
            Armenia = 8,
            Aruba = 9,
            Australia = 10,
            austria = 11,
            Azerbaijao = 12,
            Bahamas = 13,
            Bahrein = 14,
            Bangladesh = 15,
            Barbados = 16,
            Bielorrússia = 17,
            Belgica = 18,
            Belize = 19,
            Benin = 20,
            Butao = 21,
            Bolivia = 22,
            Bósnia = 23,
            Herzegovina = 24,
            Botswana = 25,
            Brasil = 26,
            Brunei = 27,
            Bulgaria = 28,
            Burkina = 29,
            Birmania = 30,
            Burundi = 31,
            Camboja = 32,
            Camarões = 33,
            Canada = 34,
            Chade = 35,
            Chile = 36,
            China = 37,
            Colombia = 38,
            Comores = 39,
            CongoRepúblicaDemocratica = 40,
            CostaRica = 41,
            Croacia = 42,
            Cuba = 43,
            Curacao = 44,
            Dinamarca = 45,
            Dominica = 46,
            RepúblicaDominicana = 47,
            Equador = 48,
            Egito = 49,
            ElSalvador = 50,
            Finlandia = 51,
            Franca = 52,
            Gabao = 53,
            Gambia = 54,
            Geórgia = 55,
            Alemanha = 56,
            Gana = 57,
            Grecia = 58,
            Grenada = 59,
            Guatemala = 60,
            HongKong = 61,
            Hungria = 62,
            Islandia = 63,
            india = 64,
            Indonesia = 65,
            Irlanda = 66,
            Italia = 67,
            Jamaica = 68,
            Japao = 69,
            Quenia = 70,
            Madagascar = 71,
            Malasia = 72,
            Malta = 73,
            Mexico = 74,
            Marrocos = 75,
            Mocambique = 76,
            Namibia = 77,
            Nepal = 78,
            NovaZelandia = 79,
            Nigeria = 80,
            Noruega = 81,
            Paraguai = 82,
            Peru = 83,
            Filipinas = 84,
            Polonia = 85,
            Portugal = 86,
            Catar = 87,
            Romenia = 88,
            Rússia = 89,
            Ruanda = 90,
            Servia = 91,
            Espanha = 92,
            Sudao = 93,
            Suecia = 94,
            Suica = 95,
            Siria = 96,
            Tailandia = 97,
            Togo = 98,
            Tonga = 99,
            Turquemenistao = 100,
            Uganda = 101,
            Ucrania = 102,
            ReinoUnido = 103,
            Uruguai = 104,
            Uzbequistao = 105,
            Vanuatu = 106,
            Venezuela = 107,
            Vietna = 108
        }
        #endregion
    }
}
